# Site settings
title: Duncan Stahl
email: duncan@spitkingdom.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dun.ky" # the base hostname & protocol for your site
twitter_username: duncanstahl
# Build settings
markdown: kramdown
